version: "2"
services:
  api:
    build: .
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    links:
      - mongodb
    depends_on:
      - mongodb
    command: npm run docker
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
